data:extend{
  {
    type = "int-setting",
    name = "sd-climate-distance",
    setting_type = "startup",
    default_value = 1200,
    minimum_value = 600,
    maximum_value = 5000,
    order = "a",
  },
  {
    type = "bool-setting",
    name = "sd-continents",
    setting_type = "startup",
    default_value = true,
    order = "b",
  },
  {
    type = "string-setting",
    name = "sd-wave-difficulty",
    setting_type = "runtime-global",
    default_value = "normal",
    allowed_values = {"relaxed", "normal", "hard", "off"},
    order = "a",
  },
  {
    type = "string-setting",
    name = "sd-wildlife",
    setting_type = "runtime-global",
    default_value = "normal",
    allowed_values = {"peaceful", "calm", "normal", "dangerous"},
    order = "c",
  },
  {
    type = "bool-setting",
    name = "sd-petrify-newcomers",
    setting_type = "runtime-global",
    default_value = true,
    order = "b",
  },
}
